def call(){
  // This calls the OWASP Dependency-Check Plugin.
  // additionalArguments: '--scan ./': This passes command-line arguments to the underlying tool. Tells the tool to scan the current directory
  // odcInstallation: 'OWASP': This tells Jenkins which specific installation of the tool to use. The string 'OWASP' must match the Name you gave the installation in Jenkins
  dependencyCheck additionalArguments: '--scan ./', odcInstallation: 'OWASP'
  // dependencyCheckPublisher: This step does not run the scan; it picks up the results of the scan and displays them in the Jenkins UI
  // pattern: '**/dependency-check-report.xml': It tells Jenkins where to look for the result file. **/ means "look in any subdirectory". dependency-check-report.xml is the default filename generated by the dependencyCheck step.
  dependencyCheckPublisher pattern: '**/dependency-check-report.xml'
}
